#!/usr/bin/env bash

APP_NAME="alpasdev"

APP_BIN_PATH="./build/install/$APP_NAME/bin/$APP_NAME"

install() {
  cecholn "YELLOW" "Building $APP_NAME..."
  if ./gradlew "$@" installdist; then
    cecholn "GREEN" "🙌 Done!"
  else
    cecholn "RED" "😿 Failed!"
  fi
}

buildJar() {
  cecholn "YELLOW" "Building jar..."
  if ./gradlew shadowJar >/dev/null 2>&1; then
    cecholn "GREEN" "🙌 Done!"
  else
    cecholn "RED" "😿 Failed!"
  fi
}

installQuietly() {
   install --quiet >/dev/null 2>&1
}

run_app() {
  if installQuietly; then
    MY_PATH=$(dirname "$0")
    MY_PATH=$( (cd "$MY_PATH" && pwd))
    APP_PATH="${MY_PATH}"

    export foobar="zsh"
    export alpas_run_mode="console"
    export alpas_root_dir="$APP_PATH"

    "$APP_BIN_PATH" "$@"

    unset alpas_run_mode
    unset alpas_root_dir
  else
    cecholn "RED" "Project build failed."
  fi
}

cecholn() {
  RED="\033[0;31m"
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  NC='\033[0m' # No Color

  printf "${!1}${2} ${NC}\n"
}

cecho() {
  RED="\033[0;31m"
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  NC='\033[0m' # No Color

  printf "${!1}${2} ${NC}"
}

if [[ $# -eq 1 ]]; then
  case "$1" in
  init)
    cecholn "YELLOW" "Initializing app..."
    gradle wrapper >/dev/null 2>&1
    install >/dev/null 2>&1
    cecholn "GREEN" "Done! Thank you for your contribution."
    ;;
  watch)
    ./gradlew shadowJar >/dev/null 2>&1
    java -jar ${APP_NAME}.jar
    ;;
  build)
    install
    ;;
  serve)
    ./gradlew shadowJar >/dev/null 2>&1
    java -jar ${APP_NAME}.jar
    ;;
  help)
    run_app --help
    ;;
  jar)
    cecholn "GREEN" "Building jar..."
    ./gradlew shadowJar >/dev/null 2>&1
    if [[ $? -eq 0 ]]; then
      cecholn "GREEN" "Completed!"
    else
      cecholn "RED" "Failed!"
    fi
    ;;
  *)
    run_app "$@"
    ;;
  esac
else
  run_app "$@"
fi
